# View
TARGET_FPS = 30
PROCESS_EVERY_N = 3
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
SHOW_FPS = True
SHOW_FACE_COUNT = True
SHOW_FINGER_COUNT = True
SHOW_HAND_TEXT = False
SHOW_FACE_TEXT = True
SHOW_BODY_TEXT = True
SHOW_VIDEO = False

# Detection
DETECT_FACE = True
DETECT_HANDS = True
DETECT_BODY = True

# Draw
DRAW_FACE = True
DRAW_HANDS = True
DRAW_BODY = True
DRAW_HAND_BOXES = False
FACE_MECH_THICKNESS = 2
FACE_CONTOUR_THICKNESS = 2
FACE_NOSE_THICKNESS = 2
FACE_DOT_RADIUS = 1
HAND_LINE_THICKNESS = 2
HAND_BOX_THICKNESS = 2
HAND_DOT_RADIUS = 2
HAND_MESH_WIDTH = 12

# Optimization
FACE_OPTIMIZED = True
HAND_OPTIMIZED = True
BODY_ACCURACY = 1

# Colors (B, G, R format for OpenCV)
# Face
FACE_COLORED = False
FACE_MESH_COLOR = (100, 100, 100)
FACE_CONTOUR_COLOR = (0, 255, 255)
FACE_NOSE_COLOR = (0, 200, 200)
FACE_DOT_COLOR = (0, 255, 0)

# Hand
HAND_COLORED = False
HAND_FILLED = False
HAND_WIREFRAME_OPACITY = 100
HAND_DOT_COLOR = (255, 255, 255)
HAND_THUMB_COLOR = (0, 0, 255)
HAND_INDEX_COLOR = (0, 255, 0)
HAND_MIDDLE_COLOR = (255, 0, 0)
HAND_RING_COLOR = (0, 255, 255)
HAND_PINKY_COLOR = (255, 0, 255)
HAND_PALM_COLOR = (255, 0, 255)
HAND_BOX_COLOR = (0, 255, 0)

# Body
BODY_COLORED = False
BODY_LINE_COLOR = (0, 255, 0)
BODY_DOT_COLOR = (0, 0, 255)
BODY_LEFT_COLOR = (255, 0, 0)
BODY_RIGHT_COLOR = (0, 0, 255)

#UI
BACKGROUND_COLOR = (0, 0, 0)
TEXT_INFO_COLOR = (0, 255, 0)
LABEL_INFO_COLOR = (255, 255, 255)

# Menu
MENU_OPEN = False